default_language_version:
    python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-path", "app/src/pyproject.toml"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--config", "app/src/pyproject.toml"]

  - repo: https://github.com/rtts/djhtml
    rev: '3.0.6'
    hooks:
      - id: djhtml

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args:
          [
            "--rcfile=app/src/pyproject.toml",
            "--load-plugins=pylint_django",
            "--django-settings-module=config.settings",
          ]
