services:
  checker_app:
    build:
      context: ./app
      target: development
    image: checker_app
    volumes:
      - ./app/src:/checker_app/src
    environment:
      - DJANGO_DEBUG=1

  celery:
    image: checker_app
    command: bash -c "cd src && celery -A config worker -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./app/src:/checker_app/src
      - media_volume:/checker_app/media/
    environment:
      - DJANGO_POSTGRES_HOST=${DJANGO_POSTGRES_HOST}
      - DJANGO_POSTGRES_PORT=${DJANGO_POSTGRES_PORT}
      - DJANGO_POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - DJANGO_POSTGRES_DATABASE=${DJANGO_POSTGRES_DATABASE}
      - MINIO_STORAGE_ACCESS_KEY=${MINIO_STORAGE_ACCESS_KEY}
      - MINIO_STORAGE_SECRET_KEY=${MINIO_STORAGE_SECRET_KEY}
    depends_on:
      - rabbitmq-broker
