apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - name: app-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
