kind: Job
apiVersion: batch/v1
metadata:
  name: migrate
spec:
  backoffLimit: 10
  template:
    spec:
      volumes:
        - name: service-config
          secret:
            secretName:  django-app-env
      containers:
        - name: migrate-app-db
          image: checker_app:latest
          command: [python, manage.py, migrate, --database, default]
          envFrom:
            - secretRef:
                name: django-app-env
        restartPolicy: OnFailure
