# Generated by Django 4.2.4 on 2023-08-20 21:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import user_files.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfile",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                upload_to=user_files.models.file_path_handler,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["py"]
                    )
                ],
            ),
        ),
    ]
