apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  type: LoadBalancer
  ports:
    - name: registry-port
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: docker-registry
