# Generated by Django 4.2.4 on 2023-08-20 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_files", "0002_userfile_created_userfile_updated_and_more"),
        ("code_checks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="check",
            name="is_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="check",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="user_files.userfile",
            ),
        ),
    ]
