# Generated by Django 4.2.4 on 2023-08-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_checks", "0002_check_created_check_is_sent_alter_check_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicTaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=200, verbose_name="Task Name")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "get_latest_by": "created",
            },
        ),
        migrations.AlterField(
            model_name="check",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="check",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="check",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("error", "Error"),
                ],
                default="new",
                max_length=8,
            ),
        ),
    ]
